name: ming_status_cli
description: Ming Status CLI - 模块化脚手架工具for Pet App平台
version: 1.0.0
repository: https://github.com/lgnorant-lu/ming_status_cli

environment:
  sdk: ^3.2.0

dependencies:
  ansi_styles: ^0.3.2
  args: ^2.4.2
  cli_util: ^0.4.0
  http: ^1.1.0
  json_annotation: ^4.8.1
  mason: ^0.1.1
  mason_api: ^0.1.1
  path: ^1.8.3
  pub_semver: ^2.1.4
  yaml: ^3.1.2

  crypto: any
dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  test: ^1.24.9
  very_good_analysis: ^5.1.0
  logging: any
