name: simple_app
description: 简单模板测试
version: 1.0.0

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  # 状态管理
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # 路由管理
  go_router: ^12.1.3

  # 数据序列化
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # UI组件
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0

  # 工具库
  intl: ^0.19.0
  equatable: ^2.0.5
  uuid: ^4.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  # 代码生成
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9

  # 资源生成
  flutter_gen_runner: ^5.4.0

  # 测试
  mockito: ^5.4.4
  build_verify: ^3.1.0

  # 代码质量
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0

  # 工具
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.8

flutter:
  uses-material-design: true

  # 资源文件
  assets:
    - assets/images/
    - assets/icons/
    - assets/colors/
    - assets/l10n/

  # 字体配置
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700

# 国际化配置
flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: l10n
  output_dir: lib/generated/l10n
