name: Ming Status CLI Validation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: stable

    - name: Install dependencies
      run: dart pub get

    - name: Run Dart analyze
      run: dart analyze --fatal-warnings

    - name: Run unit tests
      run: dart test test/unit/ --reporter=compact

    - name: Run integration tests
      run: dart test test/integration/ --reporter=compact
      continue-on-error: true

    - name: Build CLI executable
      run: dart compile exe bin/ming_status_cli.dart -o ming_status_cli

    - name: Test CLI basic functionality
      run: |
        ./ming_status_cli --version
        ./ming_status_cli --help

    - name: Install Ming Status CLI globally
      run: dart pub global activate --source path .
      continue-on-error: true

    - name: Test global CLI installation
      run: |
        export PATH="$PATH":"$HOME/.pub-cache/bin"
        ming --version || echo "Global installation test failed"
        ming --help || echo "Global help test failed"
      continue-on-error: true

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-artifacts
        path: |
          ming_status_cli
          pubspec.lock
